#!/bin/sh

# checks: ensure scripts don't overwrite custom settings
[ "$(uci -q get system.@system[0].zonename)" = "Asia/Kuala Lumpur" ] && exit 0

# root_password=""
lan_ip='192.168.0.2'
# ssid="OpenWrt"
# ssid_key="12345678"
# pppoe_name=""
# pppoe_key=""

# root passwd
if [ -n "$root_password" ]; then
  (echo "$root_password"; sleep 1; echo "$root_password") | passwd > /dev/null
fi

# /etc/config/system
uci set system.@system[0].hostname='DIR882-STA'
uci set system.@system[0].timezone='<+08>-8'
uci set system.@system[0].zonename='Asia/Kuala Lumpur'
uci set system.ntp=timeserver
uci del system.ntp.server
uci add_list system.ntp.server='ntp1.sirim.my'
uci add_list system.ntp.server='ntp2.sirim.my'

# /etc/config/network
uci del network.lan.ipaddr
uci add_list network.lan.ipaddr="$lan_ip/24"
gateway=$(echo $lan_ip | sed 's/\.[0-9]*$/\.1/') # Extract network and set gateway to .1
uci set network.lan.gateway="$gateway"
uci add_list network.lan.dns="$gateway"

# /etc/config/dhcp
uci set dhcp.lan.ignore='1'

# /etc/config/wireless
id_5g=$(uci show wireless | grep "\.band='5g'" | cut -d'=' -f1 | cut -d'.' -f2 | sed 's/[^0-9]//g') # get 5Ghz radio id
uci set  wireless.@wifi-device[$id_5g].country='MY'
uci set wireless.@wifi-device[$id_5g].disabled='0'

uci set wireless.@wifi-iface[$id_5g].mode='sta'
uci set wireless.@wifi-iface[$id_5g].ssid="${ssid}-5G@unifi"
uci set wireless.@wifi-iface[$id_5g].encryption='psk2+aes'
uci set wireless.@wifi-iface[$id_5g].key="$ssid_key"
uci set wireless.@wifi-iface[$id_5g].wds='1'

uci commit
echo "All done!"