#!/bin/sh

# checks: ensure scripts don't overwrite custom settings
[ "$(uci -q get system.@system[0].zonename)" = "Asia/Kuala Lumpur" ] && exit 0

# root_password=""
lan_ip='192.168.0.2'
# ssid="OpenWrt"
# ssid_key="12345678"
# pppoe_name=""
# pppoe_key=""

# root passwd
if [ -n "$root_password" ]; then
  (echo "$root_password"; sleep 1; echo "$root_password") | passwd > /dev/null
fi

# system
model=$(grep "machine" /proc/cpuinfo | cut -d':' -f2 | awk '{print $2}') # read device model
uci set system.@system[0].hostname="${model}-STA"
uci set system.@system[0].zonename='Asia/Kuala Lumpur'
uci set system.@system[0].timezone='<+08>-8'
uci del system.ntp.server
uci add_list system.ntp.server='my.pool.ntp.org'
uci add_list system.ntp.server='sg.pool.ntp.org'
uci commit system

# network
uci set network.lan.ipaddr="$lan_ip"
uci set network.lan.gateway='192.168.0.1'
uci set network.lan.ip6assign='64'
uci del network.lan.dns
uci add_list network.lan.dns='192.168.0.1'
uci set network.@device[0].ipv6='0'
uci set network.lan.hostname="`uci get system.@system[0].hostname`"
uci del network.wan
uci del network.wan6
uci commit network

# wireless
uci set  wireless.@wifi-device[1].country='MY'
uci set wireless.@wifi-device[1].disabled='0'

uci set wireless.@wifi-iface[1].mode='sta'
uci set wireless.@wifi-iface[1].ssid="${ssid}-5G@unifi"
uci set wireless.@wifi-iface[1].encryption='psk2+aes'
uci set wireless.@wifi-iface[1].key="$ssid_key"
uci set wireless.@wifi-iface[1].wds='1'
uci commit wireless

# dhcp
uci set dhcp.lan.ignore='1'
uci del dhcp.lan.ra
uci del dhcp.lan.dhcpv6
uci del dhcp.lan.ra_flags
uci del dhcp.lan.ra_slaac
uci commit dhcp

echo "All done!"