name: Build OpenWrt Firmware using Lienol Action

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build OpenWrt
        uses: Lienol/actions-openwrt@main
        with:
          openwrt_path: 'openwrt'
          config_path: '.config'
          diy_script_path: 'diy-part1.sh'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
          # Lienol Action Specific Options
          openwrt_repo: 'https://github.com/openwrt/openwrt'
          openwrt_branch: 'openwrt-23.05'
          upload_artifact: true
          upload_release: true
          artifact_name: 'OpenWrt_Firmware'
          release_name: 'OpenWrt Build ${{ env.DATE }}'