name: Build OpenWrt using N-l-i-t-u-s Action

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build OpenWrt
        uses: N-l-i-t-u-s/Actions-OpenWrt@main
        with:
          repository: openwrt/openwrt
          branch: openwrt-23.05
          target: bcm27xx
          subtarget: bcm2711
          config: .config
          feeds: 'src-git jerrykuku https://github.com/jerrykuku/openwrt-package'
          diy: './diy-part1.sh' # This is not used by this action, but kept for reference
          token: ${{ secrets.GITHUB_TOKEN }}