name: Build OpenWrt Manually and Reliably

on:
  push:
    branches:
      - main
    paths:
      # केवल इन फ़ाइलों/फ़ोल्डरों में बदलाव होने पर ही चलाएँ
      - '.github/workflows/build-openwrt.yml'
      - '.config'
      - 'files/**'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
          gettext git libncurses5-dev libssl-dev python3-distutils rsync unzip zlib1g-dev \
          file wget

      - name: Clone Latest OpenWrt Source Code (Master Branch)
        run: git clone https://github.com/openwrt/openwrt.git -b master openwrt

      - name: Clone Custom LuCI Apps
        run: |
          cd openwrt
          # Argon Theme
          git clone https://github.com/jerrykuku/luci-theme-argon.git package/luci-theme-argon
          git clone https://github.com/jerrykuku/luci-app-argon-config.git package/luci-app-argon-config
          # AdGuard Home
          git clone https://github.com/openwrt/packages.git -b master --depth=1 packages-master
          mv packages-master/net/adguardhome package/
          rm -rf packages-master
          cd ..

      - name: Update and Install Feeds
        working-directory: ./openwrt
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Copy Custom Build Configuration
        run: |
          cp .config openwrt/.config
          mkdir -p openwrt/files
          cp -r files/* openwrt/files/

      - name: Generate Final .config and Download Packages
        working-directory: ./openwrt
        run: |
          make defconfig
          make download -j$(nproc)

      - name: Build The Firmware
        working-directory: ./openwrt
        run: make -j$(nproc) || make -j1 V=s

      - name: Upload Firmware to Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: openwrt-rpi4-master-${{ github.run_id }}
          files: openwrt/bin/targets/bcm27xx/bcm2711/*-squashfs-factory.img.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}