name: Build Optimized OpenWrt

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/build-openwrt.yml'
      - '.config'
      - 'files/**'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Cache Build Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache
          key: ${{ runner.os }}-openwrt-${{ hashFiles('.config') }}

      - name: Install Build Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
          gettext git libncurses5-dev libssl-dev python3-distutils rsync unzip zlib1g-dev \
          file wget

      - name: Clone Latest OpenWrt Source Code (Master Branch)
        run: git clone https://github.com/openwrt/openwrt.git -b master openwrt --depth=1

      - name: Clone Custom LuCI Apps and Update Feeds
        run: |
          cd openwrt
          git clone https://github.com/jerrykuku/luci-theme-argon.git package/luci-theme-argon
          git clone https://github.com/jerrykuku/luci-app-argon-config.git package/luci-app-argon-config
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Copy Custom Build Configuration
        run: |
          cp .config openwrt/.config
          mkdir -p openwrt/files
          cp -r files/* openwrt/files/

      - name: Build The Firmware
        working-directory: ./openwrt
        run: make -j$(nproc) || make -j1 V=s

      - name: Rename Firmware File
        run: |
          mv openwrt/bin/targets/bcm27xx/bcm2711/*-squashfs-factory.img.gz openwrt/bin/targets/bcm27xx/bcm2711/openwrt-RPI4-factory.img.gz

      - name: Upload Firmware to Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: openwrt-rpi4-master-${{ github.run_id }}
          files: openwrt/bin/targets/bcm27xx/bcm2711/openwrt-Rpi4-factory.img.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
