name: Build OpenWrt Firmware using P3TERX Action

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  REPO_URL: https://github.com/openwrt/openwrt
  REPO_BRANCH: openwrt-23.05
  CONFIG_FILE: .config
  DIY_P1_SH: diy-part1.sh
  SSH_ACTIONS: false
  UPLOAD_BIN_DIR: true
  UPLOAD_FIRMWARE: true
  TZ: Asia/Kolkata

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run OpenWrt Build Action
      uses: P3TERX/Actions-OpenWrt@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        config_file: ${{ env.CONFIG_FILE }}
        diy_script_1: ${{ env.DIY_P1_SH }}
        ssh_actions: ${{ env.SSH_ACTIONS }}
        upload_bin_dir: ${{ env.UPLOAD_BIN_DIR }}
        upload_firmware: ${{ env.UPLOAD_FIRMWARE }}
        tz: ${{ env.TZ }}