name: Delete older releases, tags and workflow runs 
on:
  schedule:
    - cron: '0 0 * * 0'
    # Run every week at 12:00 AM.
  workflow_dispatch:

jobs:
  del_runs:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
    steps:
      - name: Delete releases and workflows runs
        uses: ophub/delete-releases-workflows@main
        with:
          delete_releases: true
          releases_keep_latest: 3
          delete_workflows: false
          workflows_keep_day: 3
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          delete_tags: true
          out_log: true

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 3